[project]
name = "aurora-assistente"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "marcao7814", email = "marcao7814@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "google-adk[db]>=2.2.0,<3",
    "greenlet>=3.5.6",
    "python-dotenv>=1.2.3",
]

[project.scripts]
restaurar-dados = "aurora_assistente.scripts.restaurar_dados:main"
subir-api = "aurora_assistente.api.main:executar"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
